routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use TCG\Voyager\Facades\Voyager;
use App\Http\Controllers\Home\ExamController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Home\CallbackController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Institution\EventController;
use App\Http\Controllers\Institution\StudentController;
use App\Http\Controllers\CCD\CourseController;
use App\Http\Controllers\CCD\SessionController;
use App\Http\Controllers\CCD\QuestionController;
use App\Http\Controllers\Institution\InstitutionController;
use Illuminate\Http\Request;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Institution\GradeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home.contact');
//     return view('home.index');
// });

Auth::routes();
Route::any('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::any('/privacy-policy', [HomeController::class, 'privacyPolicy'])->name('privacy-policy');
/*
Route::any('/home/callback/paystack', [CallbackController::class, 'paystackCallback'])->name('paystack-callback');
Route::any('/home/callback/rave', [CallbackController::class, 'raveCallback'])->name('rave-callback');
Route::any('/home/callback/monnify', [CallbackController::class, 'monnifyCallback'])->name('monnify-callback');
Route::any('/home/card-payment/validate-reference', [CallbackController::class, 'checkPaymentStatus'])->name('validate-payment-reference');
Route::get('/home/monnify/check-out', [HomeController::class, 'monnifyCheckout'])->name('monnify-checkout');

Route::get('/init-exam', [ExamController::class, 'selectExamBody'])->name('home.init-exam');
Route::get('/select-exam-subjects/{examBodyId}', [ExamController::class, 'selectExamSubjects'])->name('home.select-subjects');
Route::post('/register-exam', [ExamController::class, 'registerExam'])->name('home.register-exam');
Route::post('/pause-exam', [ExamController::class, 'pauseExam'])->name('home.pause-exam');
Route::get('/view-exam-result/{examNo}', [ExamController::class, 'viewResult'])->name('home.view-result');
Route::get('/preview-exam-result/{examNo}', [ExamController::class, 'previewExamResult'])->name('home.preview-result');
*/
Route::get('/exam/start/{examNo?}', [\App\Http\Controllers\Exam\ExamController::class, 'startExam'])->name('home.exam.start');
Route::get('/exam/completed/{examNo?}', [\App\Http\Controllers\Exam\ExamController::class, 'examCompleted'])->name('home.exam.completed');
Route::get('/exam/view-result-form', [\App\Http\Controllers\Exam\ExamController::class, 'viewResultForm'])->name('home.exam.view-result-form');
Route::get('/exam/view-result', [\App\Http\Controllers\Exam\ExamController::class, 'viewResult'])->name('home.exam.view-result');


Route::group(['middleware' => ['auth']], function() {
    
    Route::get('/dashboard', [UserController::class, 'index'])->name('user.dashboard');
    
    //Admin
    Route::get('/admin/dashboard', [AdminController::class, 'index'])->name('admin.dashboard');
    
    Route::resource('/admin/user', \App\Http\Controllers\Admin\UserController::class, ['as' => 'admin'])
    ->except(['create']);
    Route::get('/admin/search', [\App\Http\Controllers\Admin\UserController::class, 'search'])->name('admin.user.search');

    Route::resource('/admin/institution', \App\Http\Controllers\Admin\InstitutionController::class, ['as' => 'admin']);
    Route::get('/admin/institution/assign-user/{id}', [\App\Http\Controllers\Admin\InstitutionController::class, 'assignUserView'])->name('admin.institution.assign-user');
    Route::post('/admin/institution/assign-user/{id}', [\App\Http\Controllers\Admin\InstitutionController::class, 'assignUserStore'])->name('admin.institution.assign-user');
    
});

Route::group(['middleware' => ['auth', 'institution.user']], function() {
    
    //Institution
    Route::any('/institution/dashboard/{institution_id}', [InstitutionController::class, 'index'])->name('institution.dashboard');
    
    // Institution Event
    Route::resource('/institution/{institution_id}/event', EventController::class, ['as' => 'institution'])
    ->except(['destroy']);
//     Route::any('/institution/{institution_id}/event/{id}/update', [EventController::class, 'update'])->name('institution.event.update');
    Route::any('/institution/{institution_id}/event/suspend', [EventController::class, 'suspend'])->name('institution.event.suspend');
    Route::any('/institution/{institution_id}/event/unsuspend', [EventController::class, 'unsuspend'])->name('institution.event.unsuspend');
    Route::any('/institution/{institution_id}/event/result/{id}', [EventController::class, 'eventResult'])->name('institution.event.result');
    Route::any('/institution/{institution_id}/event/destroy/{id}', [EventController::class, 'destroy'])->name('institution.event.destroy');
    Route::any('/institution/{institution_id}/event/result-download/{id}', [EventController::class, 'downloadEventResult'])->name('institution.event.result-download');
    
    // Institution Student
    Route::resource('/institution/{institution_id}/student', StudentController::class, ['as' => 'institution'])
    ->except(['index', 'destroy']);
    Route::get('/institution/{institution_id}/student/delete/{id}', [StudentController::class, 'destroy'])->name('institution.student.destroy');
    Route::get('/institution/{institution_id}/students/{gradeId?}', [StudentController::class, 'index'])->name('institution.student.index');
    Route::get('/institution/{institution_id}/student/upload/create', [StudentController::class, 'uploadStudentsView'])->name('institution.student.upload.create');
    Route::post('/institution/{institution_id}/student/upload/store', [StudentController::class, 'uploadStudents'])->name('institution.student.upload.store');
    Route::post('/institution/{institution_id}/student/manage/suspend', [StudentController::class, 'suspend'])->name('institution.student.suspend');
    Route::post('/institution/{institution_id}/student/manage/unsuspend', [StudentController::class, 'unsuspend'])->name('institution.student.unsuspend');
    Route::get('/institution/{institution_id}/student/multi/create', [StudentController::class, 'multiStudentCreate'])->name('institution.student.multi-create');
    Route::post('/institution/{institution_id}/student/multi/create', [StudentController::class, 'multiStudentStore'])->name('institution.student.multi-store');
    Route::get('/institution/{institution_id}/student/manage/download-sample-file', [StudentController::class, 'downloadSampleExcel'])->name('institution.student.download-sample-excel');
    Route::post('/institution/{institution_id}/student/multi-delete', [StudentController::class, 'multiDelete'])->name('institution.student.multi-delete');

    Route::resource('/institution/{institution_id}/grade', GradeController::class, ['as' => 'institution']);
    
    // Institution Exam
    Route::resource('/institution/{institution_id}/exam', \App\Http\Controllers\Institution\ExamController::class, ['as' => 'institution'])
    ->except(['create', 'index', 'show']);
    Route::get('/institution/{institution_id}/exam/manage/index/{eventId?}', [\App\Http\Controllers\Institution\ExamController::class, 'index'])->name('institution.exam.index');
    Route::get('/institution/{institution_id}/exam/manage/create/{studentId?}', [\App\Http\Controllers\Institution\ExamController::class, 'create'])->name('institution.exam.create');
    Route::get('/institution/{institution_id}/exam/manage/extend/{examNo}', [\App\Http\Controllers\Institution\ExamController::class, 'extendExamTimeView'])->name('institution.exam.extend');
    Route::post('/institution/{institution_id}/exam/manage/extend/{examNo}', [\App\Http\Controllers\Institution\ExamController::class, 'extendExamTime'])->name('institution.exam.extend.store');
    Route::get('/institution/{institution_id}/exam/grade/create/{gradeId?}', [\App\Http\Controllers\Institution\ExamController::class, 'createGradeExam'])->name('institution.exam.grade.create');
    Route::post('/institution/{institution_id}/exam/grade/create/{gradeId?}', [\App\Http\Controllers\Institution\ExamController::class, 'storeGradeExam'])->name('institution.exam.grade.store');

    /**** CCD *****/ 
    // CCD Course
    Route::resource('/ccd/institution/{institution_id}/course', CourseController::class, ['as' => 'ccd'])
    ->except(['show', 'destroy']);
    Route::get('/ccd/institution/{institution_id}/course/{courseId}/delete', [CourseController::class, 'delete'])->name('ccd.course.delete');

    // CCD Session
    Route::resource('/ccd/institution/{institution_id}/session', SessionController::class, ['as' => 'ccd'])
    ->except(['index', 'create', 'store']);
    Route::any('/ccd/institution/{institution_id}/session/preview/{id}', [SessionController::class, 'preview'])->name('ccd.session.preview');
    Route::get('/ccd/institution/{institution_id}/sessions/{courseId}', [SessionController::class, 'index'])->name('ccd.session.index');
    Route::get('/ccd/institution/{institution_id}/session/create/{courseId}', [SessionController::class, 'create'])->name('ccd.session.create');
    Route::post('/ccd/institution/{institution_id}/session/store/{courseId}', [SessionController::class, 'store'])->name('ccd.session.store');

resources/views/admin/_loading.blade.php
<style>
    #loading{
        position: fixed;
        top: 0; left:0; bottom: 0; right: 0;
        background-color: #0c0c0c8a;
        display: none;
        z-index: 1000;
    }
    #loading #img-div{
        max-width: 250px;
        max-height: 250px;
        position: fixed;
        top: 30%;
        left: 55%;
    }
</style>
<div id="loading">
	<div id="img-div">
		<img src="{{assets('img/images/ajax_loader_orange_128.gif')}}" alt="" class="img-responsive" />
	</div>
</div>

resources/views/admin/_sidebar.blade.php
<style>
.app-sidebar {
    padding-top: 50px;
}
.app-sidebar__user{
    margin-bottom: 0;
    padding-top: 20px;
    padding-bottom: 20px;
    background-color: rgba(51, 51, 51, 0.4);
}
.app-sidebar__user_box{
    background-image: url("{{assets('img/images/material-bg.jpg')}}");
    background-size: cover;
}
.treeview-item {
    padding: 15px 5px 15px 20px;
}
</style>
<!-- Sidebar menu-->
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
<aside class="app-sidebar">
	<div class="app-sidebar__user_box">
    	<div class="app-sidebar__user">
    		<img class="app-sidebar__user-avatar" style="width: 48px; height: 48px; background-color: #afb7c4;"
    			src="{{assets('img/default.png')}}"
    			alt="User Image">
    		<div>
    			<p class="app-sidebar__user-name text-truncate">{{Auth::user()->username}}</p>
    			<p class="app-sidebar__user-designation text-truncate">Administrative Staff</p>
    		</div>
    	</div>
	</div>
	<ul class="app-menu">
		<li><a class="app-menu__item active" href="{{route('admin.dashboard')}}"><i
				class="app-menu__icon fa fa-dashboard"></i><span
				class="app-menu__label">Dashboard</span></a>
		</li>
		<li><a class="app-menu__item active" href="{{route('admin.user.index')}}"><i
				class="app-menu__icon fa fa-users"></i><span
				class="app-menu__label">Users</span></a>
		</li>
		<li class="treeview"><a class="app-menu__item" href="#"
			data-toggle="treeview"><i class="app-menu__icon fa fa-edit"></i><span
				class="app-menu__label">Institutions</span><i
				class="treeview-indicator fa fa-angle-right"></i></a>
			<ul class="treeview-menu">
				<li><a class="treeview-item" href="{{route('admin.institution.index')}}"><i
						class="icon fa fa-hall"></i> View Institution</a>
				</li>
				<li><a class="treeview-item" href="{{route('admin.institution.create')}}"><i
						class="icon fa fa-plus"></i> Add Institution</a>
				</li>
			</ul>
		</li>
		
		
		<?php /*
		<li><a class="treeview-item" href="{{getAddr('admin_exam_contents')}}"><i
				class="icon fa fa-eye"></i> Exam Content/Body</a>
		</li>
		<li><a class="app-menu__item" href="{{getAddr('admin_install_courses')}}"><i
				class="app-menu__icon fa fa-pie-chart"></i><span
				class="app-menu__label">Install/Uninstall Courses</span></a>
		</li>
		<li><a class="app-menu__item" href="{{getAddr('ccd_home')}}"><i
				class="app-menu__icon fa fa-pie-chart"></i><span
				class="app-menu__label">Content Developer</span></a>
		</li>
		*/?>
	</ul>
</aside>

resources/views/admin/header.blade.php
<?php 
?>
<!-- Navbar-->
<header class="app-header">
	<a class="app-header__logo text-truncate" href="{{route('admin.dashboard')}}">{{SITE_TITLE}}</a>
	<!-- Sidebar toggle button-->
	<a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
	<!-- Navbar Right Menu-->
	<ul class="app-nav">
		<li class="app-search"><input class="app-search__input" type="search"
			placeholder="Search">
			<button class="app-search__button">
				<i class="fa fa-search"></i>
			</button></li>
		<!--Notification Menu-->
		<li class="dropdown"><a class="app-nav__item" href="#"
			data-toggle="dropdown" aria-label="Show notifications"><i
				class="fa fa-bell-o fa-lg"></i></a>
			<ul class="app-notification dropdown-menu dropdown-menu-right">
				<li class="app-notification__title">You have 4 new notifications.</li>
				<div class="app-notification__content">
					<li><a class="app-notification__item" href="javascript:;"><span
							class="app-notification__icon"><span class="fa-stack fa-lg"><i
									class="fa fa-circle fa-stack-2x text-primary"></i><i
									class="fa fa-envelope fa-stack-1x fa-inverse"></i></span></span>
							<div>
								<p class="app-notification__message">Lisa sent you a mail</p>
								<p class="app-notification__meta">2 min ago</p>
							</div></a></li>
					<li><a class="app-notification__item" href="javascript:;"><span
							class="app-notification__icon"><span class="fa-stack fa-lg"><i
									class="fa fa-circle fa-stack-2x text-danger"></i><i
									class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span></span>
							<div>
								<p class="app-notification__message">Mail server not working</p>
								<p class="app-notification__meta">5 min ago</p>
							</div></a></li>
					<li><a class="app-notification__item" href="javascript:;"><span
							class="app-notification__icon"><span class="fa-stack fa-lg"><i
									class="fa fa-circle fa-stack-2x text-success"></i><i
									class="fa fa-money fa-stack-1x fa-inverse"></i></span></span>
							<div>
								<p class="app-notification__message">Transaction complete</p>
								<p class="app-notification__meta">2 days ago</p>
							</div></a></li>
					<div class="app-notification__content">
						<li><a class="app-notification__item" href="javascript:;"><span
								class="app-notification__icon"><span class="fa-stack fa-lg"><i
										class="fa fa-circle fa-stack-2x text-primary"></i><i
										class="fa fa-envelope fa-stack-1x fa-inverse"></i></span></span>
								<div>
									<p class="app-notification__message">Lisa sent you a mail</p>
									<p class="app-notification__meta">2 min ago</p>
								</div></a></li>
						<li><a class="app-notification__item" href="javascript:;"><span
								class="app-notification__icon"><span class="fa-stack fa-lg"><i
										class="fa fa-circle fa-stack-2x text-danger"></i><i
										class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span></span>
								<div>
									<p class="app-notification__message">Mail server not working</p>
									<p class="app-notification__meta">5 min ago</p>
								</div></a></li>
						<li><a class="app-notification__item" href="javascript:;"><span
								class="app-notification__icon"><span class="fa-stack fa-lg"><i
										class="fa fa-circle fa-stack-2x text-success"></i><i
										class="fa fa-money fa-stack-1x fa-inverse"></i></span></span>
								<div>
									<p class="app-notification__message">Transaction complete</p>
									<p class="app-notification__meta">2 days ago</p>
								</div></a></li>
					</div>
				</div>
				<li class="app-notification__footer"><a href="#">See all
						notifications.</a></li>
			</ul></li>
		<!-- User Menu-->
		<li class="dropdown"><a class="app-nav__item" href="#"
			data-toggle="dropdown" aria-label="Open Profile Menu"><i
				class="fa fa-user fa-lg"></i></a>
			<ul class="dropdown-menu settings-menu dropdown-menu-right">
				<li><a class="dropdown-item" href="#"><i
						class="fa fa-cog fa-lg"></i> Settings</a></li>
				<li><a class="dropdown-item" href="#"><i
						class="fa fa-user fa-lg"></i> Profile</a></li>
				<li><a class="dropdown-item" href="{{route('logout')}}"><i
						class="fa fa-sign-out fa-lg"></i> Logout</a></li>
			</ul></li>
	</ul>
</header>

resources/views/admin/index.blade.php
<?php 
$page = 'dashboard';
?>
@extends('admin.layout')

@section('dashboard_content')

<div class="app-title">
	<div>
		<h1>
			<i class="fa fa-dashboard"></i> Dashboard
		</h1>
		<p>Welcome to {{SITE_TITLE}} administrative dashboard</p>
	</div>
	<ul class="app-breadcrumb breadcrumb">
		<li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
		<li class="breadcrumb-item"><a href="#">Dashboard</a></li>
	</ul>
</div>
<!--  
<div class="row">
	<div class="col-md-6 col-lg-3">
		<div class="widget-small primary coloured-icon">
			<i class="icon fa fa-users fa-3x"></i>
			<div class="info">
				<h4>Users</h4>
				<p>
					<b>5</b>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-6 col-lg-3">
		<div class="widget-small info coloured-icon">
			<i class="icon fa fa-thumbs-o-up fa-3x"></i>
			<div class="info">
				<h4>Likes</h4>
				<p>
					<b>25</b>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-6 col-lg-3">
		<div class="widget-small warning coloured-icon">
			<i class="icon fa fa-files-o fa-3x"></i>
			<div class="info">
				<h4>Uploades</h4>
				<p>
					<b>10</b>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-6 col-lg-3">
		<div class="widget-small danger coloured-icon">
			<i class="icon fa fa-star fa-3x"></i>
			<div class="info">
				<h4>Stars</h4>
				<p>
					<b>500</b>
				</p>
			</div>
		</div>
	</div>
</div>
-->
@endsection

resources/views/admin/layout.blade.php
<?php 
$title = isset($title) ? $title : 'Admin | ' . SITE_TITLE;
?>

@extends('vali_layout')

@section('body')
	
	@include('admin.header')
	
	@include('admin._sidebar')
	@include('common.message')
	
	<main class="app-content">
	@yield('dashboard_content')
	</main>
@endsection